-------------------------------DROP PROCEDURES-------------------
IF OBJECT_ID('VADIUM.PR_BLOQUEAR_USUARIO') IS NOT NULL
DROP PROCEDURE VADIUM.PR_BLOQUEAR_USUARIO;
GO

IF OBJECT_ID('VADIUM.PR_USUARIO_LOGUEADO') IS NOT NULL
DROP PROCEDURE VADIUM.PR_USUARIO_LOGUEADO;
GO

IF OBJECT_ID('VADIUM.SP_Create_Rol') IS NOT NULL
DROP PROCEDURE [VADIUM].[SP_Create_Rol]
GO

IF OBJECT_ID('VADIUM.SP_Update_Rol') IS NOT NULL
DROP PROCEDURE [VADIUM].[SP_Update_Rol]
GO

IF OBJECT_ID('VADIUM.SP_Update_Funcionalidad_Por_Rol') IS NOT NULL
DROP PROCEDURE [VADIUM].[SP_Update_Funcionalidad_Por_Rol]
GO

IF OBJECT_ID('VADIUM.PR_INHABILITAR_ROL') IS NOT NULL
DROP PROCEDURE [VADIUM].[PR_INHABILITAR_ROL]
GO

IF OBJECT_ID('VADIUM.SP_Get_Funcionalidades_Rol') IS NOT NULL
DROP PROCEDURE [VADIUM].[SP_Get_Funcionalidades_Rol]
GO

IF OBJECT_ID('VADIUM.PR_Get_Funcionalidades') IS NOT NULL
DROP PROCEDURE [VADIUM].[PR_Get_Funcionalidades]
GO

IF OBJECT_ID('VADIUM.PR_Get_Roles') IS NOT NULL
DROP PROCEDURE [VADIUM].[PR_Get_Roles]
GO
IF OBJECT_ID('VADIUM.PR_LOGIN') IS NOT NULL
DROP PROCEDURE [VADIUM].[PR_LOGIN]
GO

IF OBJECT_ID('VADIUM.SP_Get_Usuario_Rol') IS NOT NULL
DROP PROCEDURE [VADIUM].[SP_Get_Usuario_Rol]
GO

IF OBJECT_ID('VADIUM.PR_DATOS_INSERT_DATOS_INICIALES') IS NOT NULL
DROP PROCEDURE VADIUM.PR_DATOS_INSERT_DATOS_INICIALES;
GO
IF OBJECT_ID('VADIUM.PR_MIGRACION') IS NOT NULL
DROP PROCEDURE VADIUM.PR_MIGRACION;
GO
------------------------------DROP TRIGGERS ---------------------------------
IF OBJECT_ID('VADIUM.TriggerNuevaEmpresa') IS NOT NULL
DROP TRIGGER VADIUM.TriggerNuevaEmpresa
GO
IF OBJECT_ID('VADIUM.TriggerNuevoCliente') IS NOT NULL
DROP TRIGGER VADIUM.TriggerNuevoCliente
GO
-----------------------DROP TABLES-------------------------------
IF OBJECT_ID('VADIUM.ROL_POR_FUNCIONALIDAD') IS NOT NULL
DROP TABLE [VADIUM].ROL_POR_FUNCIONALIDAD
GO
IF OBJECT_ID('VADIUM.ROL_POR_USUARIO') IS NOT NULL
DROP TABLE [VADIUM].ROL_POR_USUARIO
GO
IF OBJECT_ID('VADIUM.ROL') IS NOT NULL
DROP TABLE [VADIUM].ROL
GO
IF OBJECT_ID('VADIUM.FUNCIONALIDAD') IS NOT NULL
DROP TABLE [VADIUM].FUNCIONALIDAD
GO

IF OBJECT_ID('VADIUM.PUBLICACION') IS NOT NULL
DROP TABLE [VADIUM].PUBLICACION
GO

IF OBJECT_ID('VADIUM.ESTADO') IS NOT NULL
DROP TABLE [VADIUM].ESTADO
GO
IF OBJECT_ID('VADIUM.RUBRO') IS NOT NULL
DROP TABLE [VADIUM].RUBRO
GO
IF OBJECT_ID('VADIUM.GRADO') IS NOT NULL
DROP TABLE [VADIUM].GRADO
GO

IF OBJECT_ID('VADIUM.TIPOUBICACION') IS NOT NULL
DROP TABLE [VADIUM].TIPOUBICACION
GO

IF OBJECT_ID('VADIUM.EMPRESA') IS NOT NULL
DROP TABLE [VADIUM].EMPRESA
GO

IF OBJECT_ID('VADIUM.UBICACION') IS NOT NULL
DROP TABLE [VADIUM].UBICACION
GO
IF OBJECT_ID('VADIUM.ITEMFACTURA') IS NOT NULL
DROP TABLE [VADIUM].ITEMFACTURA
GO
IF OBJECT_ID('VADIUM.FACTURA') IS NOT NULL
DROP TABLE [VADIUM].FACTURA
GO

IF OBJECT_ID('VADIUM.PREMIO_POR_CLIENTE') IS NOT NULL
DROP TABLE [VADIUM].PREMIO_POR_CLIENTE
GO
IF OBJECT_ID('VADIUM.PREMIO') IS NOT NULL
DROP TABLE [VADIUM].PREMIO
GO


IF OBJECT_ID('VADIUM.TARJETADECREDITO') IS NOT NULL
DROP TABLE [VADIUM].TARJETADECREDITO
GO
IF OBJECT_ID('VADIUM.DIRECCION') IS NOT NULL
DROP TABLE VADIUM.DIRECCION
GO
IF OBJECT_ID('VADIUM.CLIENTE') IS NOT NULL
DROP TABLE [VADIUM].CLIENTE
GO

IF OBJECT_ID('VADIUM.USUARIO') IS NOT NULL
DROP TABLE [VADIUM].USUARIO
GO

-----------------------DROP SCHEMA--------------------------------
IF SCHEMA_ID('VADIUM') IS NOT NULL
	DROP SCHEMA [VADIUM]
GO